### ISSUE TITLE
CORS policy doesn't allow requests from localhost

### ISSUE THREAD

**Issue by blauks** [IT2901-SINTEF01/backend#29]
### Problem
When I send a GraphQL request to the backend I get a "CORS Missing Allow Origin" error.
![image](https://user-images.githubusercontent.com/33070123/108375385-2f0fd580-7202-11eb-897d-e317a680bdcc.png)

### Setup
I ran the backend locally with `dotnet run`, on my Mac (Big sur v11.2.1) with Firefox (v85.0.2.)

### Relevant information
I call the backend from my React frontend, running on http://localhost:3000, with this query.
```typescript
const client = new ApolloClient({
    link: createHttpLink({ uri: 'https://localhost:5001/graphql' }),
    cache: new InMemoryCache(),
});

client
    .query({
        query: gql`
            query {
                forecast(lat: 63.4187703, lon: 10.403743) {
                    forecastGeometry {
                        coordinates
                        type
                    }
                    forecastProperties {
                        meta {
                            updatedAt
                            units {
                                airTemperature
                                precipitationAmount
                                windSpeed
                            }
                        }
                        timeseries {
                            forecastData {
                                instant {
                                    details {
                                        airTemperature
                                        precipitationAmount
                                        windSpeed
                                    }
                                }
                            }
                            time
                        }
                    }
                }
            }
        `,
    })
    .then((result) => console.log(result))
    .catch((e) => console.log(e));
```

Do not know if this is relevant, but I did not get any other stack traces than that the query is missing 
```
System.InvalidOperationException: Cannot execute request if no query is specified
   at GraphQL.DocumentExecuter.ExecuteAsync(ExecutionOptions options) in /_/src/GraphQL/Execution/DocumentExecuter.cs:line 56
   at GraphQL.Server.Internal.DefaultGraphQLExecuter`1.ExecuteAsync(String operationName, String query, Inputs variables, IDictionary`2 context, IServiceProvider requestServices, CancellationToken cancellationToken) in /_/src/Core/Internal/DefaultGraphQLExecuter.cs:line 54
   at GraphQL.Server.Transports.AspNetCore.GraphQLHttpMiddleware`1.InvokeAsync(HttpContext context) in /_/src/Transports.AspNetCore/GraphQLHttpMiddleware.cs:line 144
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by blauks** [comment]
If any information that would be useful is missing just @ me.

**Comment by FredrikAugust** [comment]
Might you be able to fix this on the frontend by using the proxy configuration in `package.json`?

**Comment by FredrikAugust** [comment]
Could you also check if the error is present with the docker image installation? You can access the backend over port 5000 without https.

**Comment by blauks** [comment]
It did not work with the proxy, and I have the same problem with Docker using port 5000.

**Comment by FredrikAugust** [comment]
I'll take a look later today.

**Comment by FredrikAugust** [comment]
I got it to work with using proxies on frontend. 

Steps to reproduce: 
- Add to package.json:
```json
    "proxy": "http://localhost:5000",
```
- Code used for testing
```tsx
            <button
                onClick={() =>
                    fetch('/graphql', {
                        method: 'POST',
                        headers: { 'Content-Type': 'application/json' },
                        body: `{"operationName":null,"variables":{},"query":"{ forecast { forecastGeometry { coordinates } } } "}`,
                    })
                }
            >
                test
            </button>
```

Remember that when proxying you need to make a request to the host you're serving the app from. This is done by default when omitting the host in the `fetch` request, and only including the path.
